# Generated by Django 6.0 on 2026-02-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('HAQORATLI', 'haqoratli'), ("YOLG'ON", "yolg'on"), ('WAITING', 'waiting'), ('ACTIVE', 'active')], default='waiting', max_length=20),
        ),
    ]
